# Custom network for frontend <-> backend
networks:
  mern-net:

services:
  # Backend Service
  backend:
    build: ./backend          # Build image from backend/Dockerfile
    container_name: backend
    ports:
      - "4000:4000"           # (optional) expose backend to host
    networks:
      - mern-net              # join shared network

  # Frontend Service
  frontend:
    build: ./frontend         # Build image from frontend/Dockerfile
    container_name: frontend
    depends_on:
      - backend               # start backend first
    ports:
      - "3000:3000"           # host 3000 -> container 3000
    networks:
      - mern-net              # can reach http://backend:4000

